/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'evan' at '8/17/16 6:54 PM' with Gradle 3.0
 *
 * @author evan, @date 8/17/16 6:54 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
