import org.testng.annotations.*;
import static org.testng.Assert.assertTrue;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library --with testng'
 * by 'evan' at '8/17/16 6:54 PM' with Gradle 3.0
 *
 * @author evan, @date 8/17/16 6:54 PM
 */
public class LibraryTest {
    @Test public void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }
}
