package com.github.aeroevan;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'evan' at '8/17/16 6:54 PM' with Gradle 3.0
 *
 * @author evan, @date 8/17/16 6:54 PM
 */
public class Library {
    private static final int DEFAULT_LENGTH = 12;
    private static final char[] BASE32 = {'0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'b', 'c', 'd', 'e', 'f',
            'g', 'h', 'j', 'k', 'm', 'n', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z'};
    private enum Encode {
        LONGITUDE,
        LATITUDE
    }
    public boolean someLibraryMethod() {
        return true;
    }

    public String encode(double latitude, double longitude) {
        return encode(latitude, longitude, DEFAULT_LENGTH);
    }

    public String encode(double latitude, double longitude, int length) {
        //lat_interval, lon_interval = (-90.0, 90.0), (-180.0, 180.0)
        double[] latInterval = {-90.0, 90.0};
        double[] lonInterval = {-180.0, 180.0};
        StringBuilder sb = new StringBuilder(length);
        Encode encode = Encode.LONGITUDE;
        while (sb.length() < length) {
            switch (encode) {
                case LONGITUDE:
                    double mid = (lonInterval[0] + lonInterval[1]) / 2.0;
                    //
                    break;
                case LATITUDE:
                    //
                    break;
                default:
                    break;
            }

        }
        return sb.toString();
    }
}
